<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AddToCart</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0546b569-fe85-4248-b860-426e2b155115</testSuiteGuid>
   <testCaseLink>
      <guid>82e83281-68d5-40db-9f83-6e075c98e9f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login_Page/Positive_Case/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2d1bd5a7-4d67-4c0c-884f-6f003cee466e</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/dataUser</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2d1bd5a7-4d67-4c0c-884f-6f003cee466e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>d5364af9-9adf-489d-ac9e-3abfec869b3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2d1bd5a7-4d67-4c0c-884f-6f003cee466e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>9782d047-30fa-49f6-8e5e-c9de18c1ece8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d27ff21-7ae0-4b0d-8b23-5338260c1764</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product_Page/AddToCart_Products</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>40712739-e2a7-4209-94d9-0e2328b17caa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/productData (1)</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>40712739-e2a7-4209-94d9-0e2328b17caa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>productsName</value>
         <variableId>0ec49a29-9b6c-4935-a40e-698b47b129b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
